version: '3.8'

services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile.relay
    container_name: websocket-relay
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - relay-network

  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.docker:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - relay-network
    depends_on:
      - relay

volumes:
  caddy_data:
  caddy_config:

networks:
  relay-network:
    driver: bridge