name: Deploy Conference Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        BUILD_COMMIT=${{ github.sha }}
        BUILD_BY="GitHub Actions"
        BUILD_REF="${{ github.ref }}"
        
        echo "Building Docker image..."
        if ! docker build -t webp-conference:latest \
          --build-arg BUILD_TIME="$BUILD_TIME" \
          --build-arg BUILD_COMMIT="$BUILD_COMMIT" \
          --build-arg BUILD_BY="$BUILD_BY" \
          --build-arg BUILD_REF="$BUILD_REF" \
          . 2>&1 | tee build.log; then
          echo "Docker build failed. Last 50 lines of output:"
          tail -50 build.log
          echo "::error::Docker build failed. Check the logs above."
          exit 1
        fi
        
        docker save webp-conference:latest | gzip > conference.tar.gz
    
    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build.log
        retention-days: 7
    
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 91.99.159.21
        username: root
        key: ${{ secrets.HETZNER_SSH_KEY }}
        source: "conference.tar.gz,docker-compose.yml,Caddyfile"
        target: "/root/conference"
    
    - name: Deploy to Hetzner
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 91.99.159.21
        username: root
        key: ${{ secrets.HETZNER_SSH_KEY }}
        script: |
          # Stop existing containers
          cd /root/conference || mkdir -p /root/conference
          docker-compose down || true
          
          # Clean up old images
          docker image prune -f
    
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 91.99.159.21
        username: root
        key: ${{ secrets.HETZNER_SSH_KEY }}
        source: "conference.tar.gz,docker-compose.yml,Caddyfile"
        target: "/root/conference"
    
    - name: Deploy on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 91.99.159.21
        username: root
        key: ${{ secrets.HETZNER_SSH_KEY }}
        script: |
          cd /root/conference || exit 1
          
          # Stop and remove old containers
          docker-compose down || true
          docker rm -f webp-conference caddy-proxy || true
          
          # Load new image
          docker load < conference.tar.gz
          
          # Start services fresh
          docker-compose up -d --force-recreate
          
          # Wait for services to be healthy
          sleep 5
          
          # Check status and health endpoint
          docker-compose ps
          echo "Testing health endpoint:"
          curl -s http://localhost:3001/health | head -20 || echo "Health endpoint not ready yet"
    
    - name: Update GitHub Pages
      run: |
        echo "GitHub Pages will automatically deploy from main branch"
        echo "Visit: https://miguelemosreverte.github.io/videocall/"
        echo "Server: wss://91.99.159.21.nip.io/ws"